title: Bikini Bottom Discord
description: The largest, most active, coolest Spongebob Discord server!
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
defaults:
  - scope:
      path: ""
    values:
      og_image: "https://cdn.discordapp.com/emojis/718369341816700958.png"
